# practice 4. Logistic Regression 

데이터 셋 링크: https://www.kaggle.com/datasets/jsphyg/weather-dataset-rattle-package?select=weatherAUS.csv  
참고자료: https://www.kaggle.com/code/prashant111/logistic-regression-classifier-tutorial

이 데이터 집합에는 호주 전역의 여러 위치에서 약 10년간의 일일 기상 관측 데이터가 포함되어 있습니다. 내일 비가 올지 여부를 나타낸 RainTomorrow 여부를 예측하는 logistic regression 모델을 학습시키고, 성능을 측정하고, 결과를 해석해보세요.

In [1]:
from utils import load_weather_dataset

x_train, x_test, y_train, y_test = load_weather_dataset()

In [2]:
x_train

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday
92882,2016-05-24,GoldCoast,17.7,25.3,0.0,NaN,NaN,SSE,43.0,S,...,24.0,41.0,40.0,1017.6,1015.2,NaN,NaN,23.5,23.2,No
98353,2014-04-23,Adelaide,8.1,20.9,0.0,3.6,9.2,WNW,22.0,NaN,...,9.0,63.0,34.0,1018.8,1014.9,NaN,NaN,14.6,20.1,No
49669,2010-09-08,Tuggeranong,-0.7,14.2,0.0,NaN,NaN,N,33.0,NNE,...,11.0,65.0,40.0,1027.4,1022.6,NaN,NaN,7.6,13.5,No
113818,2015-04-16,Witchcliffe,6.4,20.1,0.0,NaN,NaN,SE,28.0,NaN,...,19.0,72.0,52.0,1033.5,1029.5,NaN,NaN,15.0,19.8,No
50325,2012-07-26,Tuggeranong,2.4,11.9,3.0,NaN,NaN,N,22.0,NNW,...,2.0,85.0,79.0,1015.1,1011.3,NaN,NaN,9.2,10.8,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41239,2013-11-26,Williamtown,13.9,22.8,5.0,5.2,7.9,SSE,48.0,WSW,...,33.0,52.0,45.0,1015.8,1016.0,6.0,2.0,18.9,21.7,Yes
55985,2011-06-02,Ballarat,3.3,14.7,0.0,NaN,NaN,N,46.0,NNE,...,30.0,84.0,70.0,1026.4,1022.0,2.0,NaN,10.1,13.7,No
32399,2014-06-01,Sydney,14.8,20.7,11.2,5.0,0.4,W,46.0,NW,...,26.0,87.0,70.0,1020.5,1018.0,7.0,8.0,17.0,17.8,Yes
82584,2013-08-03,Dartmoor,5.0,13.5,2.2,1.4,4.8,WNW,61.0,N,...,20.0,95.0,79.0,1009.9,1006.5,NaN,NaN,9.4,13.4,Yes
121909,2012-01-23,Perth,19.7,34.7,0.0,8.2,11.8,ESE,44.0,SSE,...,15.0,60.0,48.0,1013.2,1010.0,5.0,7.0,25.2,31.5,No

In [3]:
y_train

92882      No
98353     Yes
49669      No
113818     No
50325     Yes
         ...
41239      No
55985      No
32399      No
82584     Yes
121909     No
Name: RainTomorrow, Length: 116368, dtype: object